loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

dependencies {
    implementation project(":common")
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    implementation 'org.mariuszgromada.math:MathParser.org-mXparser:5.2.1'
    include 'org.mariuszgromada.math:MathParser.org-mXparser:5.2.1'
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

jar {
    from project(":common").sourceSets.main.output
}

sourcesJar {
    from project(":common").sourceSets.main.allSource
}

