buildscript {
    configurations.classpath {
        resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    }
}

plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.20' apply false
}

subprojects {
    apply plugin: "java"
    apply plugin: "net.fabricmc.fabric-loom"
    apply plugin: "maven-publish"

    base.archivesName = rootProject.archives_base_name
    version = rootProject.mod_version

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 25
    }

    java {
        withSourcesJar()
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    repositories {
        mavenCentral()
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.terraformersmc.com/releases/" }
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://maven.blamejared.com" }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    }

    // Define reusable exclusion patterns
    def exclusionPatterns = ['**/*.aup3', '**/.xdp-*', '**/*.kra', '**/*~*']
    processResources {
        exclusionPatterns.each {
            pattern -> exclude pattern
        }
    }
    sourcesJar {
        exclusionPatterns.each {
            pattern -> exclude pattern
        }
    }
}