def getAppVersion = { ->
    try {
        def proc = new ProcessBuilder("git", "tag", "--points-at", "HEAD")
                .directory(rootProject.projectDir)
                .redirectErrorStream(true)
                .start()
        def tag = proc.inputStream.getText("UTF-8").trim()
        proc.waitFor()
        return tag.isEmpty() ? "${rootProject.minecraft_version}-SNAPSHOT" : tag
    } catch (Exception e) {
        println "Warning: ${e.message}, is git installed?"
        return "${rootProject.minecraft_version}-DEV"
    }
}

allprojects {
    group = rootProject.group_id
    version = getAppVersion()
}

subprojects {
    apply plugin: "java"
    apply plugin: "maven-publish"

    repositories {
        maven { name = "Fabric"; url = "https://maven.fabricmc.net/" }
        maven { name = "Forge"; url = "https://maven.minecraftforge.net/" }
        maven { name = "NeoForge"; url = "https://maven.neoforged.net/releases/" }
        maven { name = "BlameJared"; url = "https://maven.blamejared.com/" }
        maven { name = "Shedaniel"; url = "https://maven.shedaniel.me/" }
        maven { name = "Terraformers"; url = "https://maven.terraformersmc.com/releases/" }
        maven { name = "TeamResourceful"; url = "https://maven.teamresourceful.com/repository/maven-public/" }
        maven { name = "CurseMaven"; url = "https://cursemaven.com" }
        mavenCentral()
    }

    base {
        archivesName = "${rootProject.archives_base_name}-${project.name}"
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 25
    }

    tasks.withType(ProcessResources).configureEach {
        exclude "**/*.aup3", "**/.xdp-*", "**/*.kra", "**/*~*"
    }

    tasks.named("sourcesJar").configure {
        exclude "**/*.aup3", "**/.xdp-*", "**/*.kra", "**/*~*"
    }

    publishing {
        repositories {
            maven {
                name = "reposiliteRepository"
                url = uri("https://maven.conczin.net/Artifacts")
                credentials {
                    username = System.getenv("MAVEN_USERNAME")
                    password = System.getenv("MAVEN_TOKEN")
                }
            }
        }
    }
}
