org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

enabled_platforms=fabric,neoforge

minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3

# Fabric API
fabric_version=0.138.3+1.21.10
parchment_version=1.21:2024.07.28

group_id=net.conczin
archives_base_name=immersive_aircraft

fabric_loader_version=0.18.1
fabric_api_version=0.138.3+1.21.10

cloth_version=20.0.149
mod_menu_version=16.0.0-rc.1

neoforge_version=21.10.64

jei_version=26.2.0.27
rei_version=21.9.812
