org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

enabled_platforms=fabric

minecraft_version=1.21.11
parchment_version=1.21.1:2024.11.17

group_id=net.conczin
archives_base_name=immersive_aircraft

fabric_loader_version=0.19.2
fabric_api_version=0.141.4+1.21.11

cloth_version=21.11.153
mod_menu_version=17.0.0

neoforge_version=21.11.42

jei_version=27.4.0.22
rei_version=21.11.814

ad_astra_version=1.20.1:1.15.18
man_of_many_planes_version=1.21.1-SNAPSHOT
immersive_machinery=1.21.1-SNAPSHOT