pluginManagement {
    repositories {
        maven { name = "Fabric"; url = "https://maven.fabricmc.net/" }
        maven { name = "Forge"; url = "https://maven.minecraftforge.net/" }
        maven { name = "NeoForge"; url = "https://maven.neoforged.net/releases/" }
        maven { name = "Sponge"; url = "https://repo.spongepowered.org/repository/maven-public/" }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "org.gradle.toolchains.foojay-resolver-convention" version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        maven { name = "Fabric"; url = "https://maven.fabricmc.net/" }
        maven { name = "Forge"; url = "https://maven.minecraftforge.net/" }
        maven { name = "NeoForge"; url = "https://maven.neoforged.net/releases/" }
        maven { name = "BlameJared"; url = "https://maven.blamejared.com/" }
        maven { name = "Shedaniel"; url = "https://maven.shedaniel.me/" }
        maven { name = "Terraformers"; url = "https://maven.terraformersmc.com/releases/" }
        maven { name = "TeamResourceful"; url = "https://maven.teamresourceful.com/repository/maven-public/" }
        maven { name = "CurseMaven"; url = "https://cursemaven.com" }
        mavenCentral()
    }
}

rootProject.name = "immersive-aircraft"

include("fabric")
include("forge")
include("neoforge")
