plugins {
    id "idea"
    id "eclipse"
    id "net.minecraftforge.gradle" version "${forge_gradle_version}"
}

sourceSets {
    main {
        java.srcDir rootProject.file("common/src/main/java")
        resources.srcDir rootProject.file("common/src/main/resources")

        java.exclude "immersive_aircraft/config/ModMenuIntegration.java"
        java.exclude "immersive_aircraft/config/ConfigScreen.java"
        java.exclude "immersive_aircraft/combat/JEICCombat.java"
        java.exclude "immersive_aircraft/combat/REICombat.java"
        java.exclude "immersive_aircraft/forge/compat/REICombatForge.java"
    }
}

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir("run")

            systemProperty "eventbus.api.strictRuntimeChecks", "true"
            systemProperty "forge.enabledGameTestNamespaces", "immersive_aircraft"
        }

        register("client")

        register("server") {
            args "--nogui"
        }

        register("gameTestServer")

        register("data") {
            workingDir = layout.projectDirectory.dir("run-data")
            args "--mod", "immersive_aircraft", "--all",
                    "--output", layout.projectDirectory.dir("src/generated/resources"),
                    "--existing", layout.projectDirectory.dir("src/main/resources")
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor "net.minecraftforge:eventbus-validator:7.0.1"

    implementation "org.mariuszgromada.math:MathParser.org-mXparser:5.2.1"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", rootProject.minecraft_version
    inputs.property "minecraft_version_range", rootProject.minecraft_version_range
    inputs.property "forge_version", rootProject.forge_version
    inputs.property "loader_major", rootProject.forge_version.split("\\.")[0]

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version,
                "minecraft_version": rootProject.minecraft_version,
                "minecraft_version_range": rootProject.minecraft_version_range,
                "forge_version": rootProject.forge_version,
                "loader_major": rootProject.forge_version.split("\\.")[0]
    }
}

jar {
    from(rootProject.file("LICENSE")) {
        rename { "${it}_${project.name}" }
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = rootProject.archives_base_name
            version = "${project.version}+forge"
            from components.java
        }
    }
}
