plugins {
    id "java-library"
    id "net.neoforged.moddev" version "${neoforge_moddev_version}"
}

sourceSets {
    main {
        java.srcDir rootProject.file("common/src/main/java")
        resources.srcDir rootProject.file("common/src/main/resources")
        java.exclude "immersive_aircraft/config/ModMenuIntegration.java"
    }
}

neoForge {
    version = project.neoforge_version
    accessTransformers = project.files("src/main/resources/META-INF/accesstransformer.cfg")

    parchment {
        minecraftVersion = rootProject.parchment_version.split(":")[0]
        mappingsVersion = rootProject.parchment_version.split(":")[1]
    }

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument "--nogui"
        }
    }

    mods {
        "immersive_aircraft" {
            sourceSet sourceSets.main
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    jarJar(implementation("org.mariuszgromada.math:MathParser.org-mXparser:5.2.1")) {
        version {
            strictly "[5.2.1]"
            prefer "5.2.1"
        }
    }
    additionalRuntimeClasspath "org.mariuszgromada.math:MathParser.org-mXparser:5.2.1"

    compileOnly "me.shedaniel.cloth:cloth-config-neoforge:${cloth_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    compileOnly("me.shedaniel:RoughlyEnoughItems-api-neoforge:${rei_version}") { transitive false }
    compileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin:${rei_version}") { transitive false }
    compileOnly("earth.terrarium.adastra:ad_astra-forge-${ad_astra_version}") { transitive false }
}

def generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    def replaceProperties = [
            minecraft_version: rootProject.minecraft_version,
            loader_major     : "1",
            version          : project.version
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

jar {
    from(rootProject.file("LICENSE")) {
        rename { "${it}_${project.name}" }
    }
}

publishing {
    publications {
        mavenNeoForge(MavenPublication) {
            artifactId = rootProject.archives_base_name
            version = "${project.version}+neoforge"
            from components.java
        }
    }
}
